name: Java lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  java-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: hello world 
        run: echo Hello World


